### ISSUE TITLE
Additional output_vars for surface_bmi

### ISSUE THREAD

**Issue by SnowHydrology** [NOAA-OWP/noah-mp-modular#25]
Consider adding additional diagnostic variables to surface_bmi output_vars so they can be written to Nextgen output.

**Comment by SnowHydrology** [comment]
@lcunha0118, What variables would be useful for you when writing output data?

**Comment by lcunha0118** [comment]
For checking it would be good to include some variable related to snow accumulation/melting (SWE?). I am not familiar enough with the variables within the model to tell you which one. 

For the other models we are also outputting rainfall, as a minimum way to check things. 

That being said, at this moment ngen does not output to file anything from NOAH-MP. So not sure if I will be able to use the variables.

**Comment by ajkhattak** [comment]
One variable that is needed for the freeze-thaw model is the **ground surface temperature** that is used as a boundary condition in the model.

**Comment by SnowHydrology** [comment]
@andywood Should we also include all of the variables from `OutputModule.f90`? This will allow Nextgen to write them to file when the model is running in the framework.

**Comment by andywood** [comment]
Hi Keith,

I'd say we should just tailor the output vars to what we think we'll need
(or the framework will need) so that it's relatively efficient and the
output has as small a footprint as it can.  I think T2B may be bare ground
temperature; I don't know if that accounts for whether the ground is under
snow or not.

Cheers,
-Andy

**Comment by SnowHydrology** [comment]
@andywood I believe T2B is the 2 m air temperature above the bare ground portion of the model space.

**Comment by SnowHydrology** [comment]
Closing this for now as I've added ground temperature and snow water equivalent to the BMI output vars. Please add a new issue if any of you require additional output vars.
