### ISSUE TITLE
consider whether a specific 'derived variables' routine is needed

### ISSUE THREAD

**Issue by andywood** [NOAA-OWP/noah-mp-modular#4]
depending how extensive this need is, it may be useful to collect variable transformations now housed in the noah-mp drivers into a specific routine.

**Comment by SnowHydrology** [comment]
UtilitiesModule implemented in <https://github.com/NOAA-OWP/noah-mp-modular/pull/7>. It can incorporate additional code as we identify more derived vars to include.
